---
- name: k3s
  hosts: localhost

  vars_files:
    - ./vars.yml
  roles:
    - role: geerlingguy.docker

  tasks:

  - name: Deploy latest version of mariadb chart
    kubernetes.core.helm:
      name: test
      validate_certs: no
      chart_ref: bitnami/mariadb
      release_namespace: tournaments
      create_namespace: true
      kubeconfig: "kubeconfig"
      values_files:
        - ../chartbot/valuesdb.yml

  - name: Copy sql file to pod
    kubernetes.core.k8s_cp:
      validate_certs: no
      kubeconfig: "kubeconfig"
      namespace: tournaments
      pod: test-mariadb-0
      remote_path: "/tmp/db.sql"
      local_path: "../chartbot/db.sql"
    ignore_errors: yes

  - name: Copy script to pod
    kubernetes.core.k8s_cp:
      validate_certs: no
      kubeconfig: "kubeconfig"
      namespace: tournaments
      pod: test-mariadb-0
      remote_path: "/tmp/script-import" 
      local_path: "../chartbot/script-import"
    ignore_errors: yes

  - name: Import sql file in pod mariadb
    kubernetes.core.k8s_exec:
      validate_certs: no
      kubeconfig: "kubeconfig"
      namespace: tournaments
      pod: test-mariadb-0
      command: sh /tmp/script-import
    register: exec

  - name: Install my helm chart bot
    kubernetes.core.helm:
      validate_certs: no
      kubeconfig: "kubeconfig"
      name: bot
      chart_ref: "/home/foilv/chartbot/"
      release_namespace: tournaments
      values_files:
        - ../chartbot/values.yml

